#!/bin/zsh

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"

if [[ ! -r "$NVM_DIR/nvm.sh" ]]; then
  print -u2 "NVM is not installed at $NVM_DIR"
  exit 1
fi

source "$NVM_DIR/nvm.sh"

webtorrent_cli="$HOME/.local/share/dotfiles-node-tools/node_modules/.bin/webtorrent"
if [[ ! -x "$webtorrent_cli" ]]; then
  print -u2 "webtorrent-cli is not installed. Run 'nvm use 20 && make node-dependencies' from the dotfiles repository."
  exit 1
fi

nvm exec --silent 20 "$webtorrent_cli" "$@"
