#!/bin/zsh

kitty_dir="${0:a:h}"
theme="$kitty_dir/theme.conf"

target="$kitty_dir/themes/rose-pine-dawn.conf"

if [[ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" = "Dark" ]]; then
    target="$kitty_dir/themes/rose-pine.conf"
fi

# nvim --server "/tmp/nvim.pipe" --remote-expr "execute('set background=$neovim_background')" 
# nvim --server "/tmp/nvim.pipe" --remote-expr "execute('colorscheme $neovim_colorscheme')" 

rm -rf "$theme"
ln -s "$target" "$theme"

for pid in "$(ps -x | grep '/Applications/kitty.app/Contents/MacOS/kitty' | grep -v grep | awk '{ print $1 }')"; do
    kill -SIGUSR1 $pid
done

